#!/bin/bash
echo legajo
read legajo
echo password
read password

ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.190 "/ppp secret add name=$legajo password=$password service=pptp profile=vpn_balat"
ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.191 "/ppp secret add name=$legajo password=$password service=pptp profile=vpn_balat"
ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.192 "/ppp secret add name=$legajo password=$password service=pptp profile=vpn_balat"
ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.193 "/ppp secret add name=$legajo password=$password service=pptp profile=vpn_staff"
