#!/bin/bash
echo legajo
read legajo

ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.190 "/ppp secret remove \"$legajo\" "
ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.191 "/ppp secret remove \"$legajo\" "
ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.192 "/ppp secret remove \"$legajo\" "
ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.193 "/ppp secret remove \"$legajo\" "
ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.190 "/ppp secret remove \"$legajo\" "
ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.191 "/ppp secret remove \"$legajo\" "
ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.192 "/ppp secret remove \"$legajo\" "
ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.193 "/ppp secret remove \"$legajo\" "

