#!/bin/bash
echo ---pbx1
ssh root@192.1.2.221  "asterisk -rx 'sip show peers'| grep '192.1.25\|172.16' | sort | uniq | wc|awk '{print \$1}'"
echo -
ssh root@192.1.2.221  "asterisk -rx 'sip show peers'| grep '192.1.25\|172.16' | sort | uniq| cut -f1 -d\/ "
echo ---pbx2
ssh root@192.1.2.220  "asterisk -rx 'sip show peers'| grep '192.1.25\|172.16' | sort | uniq | wc|awk '{print \$1}'"
echo -
ssh root@192.1.2.220  "asterisk -rx 'sip show peers'| grep '192.1.25\|172.16' | sort | uniq| cut -f1 -d\/ "
echo ---pbx3
ssh root@192.1.2.223  "asterisk -rx 'sip show peers'| grep '192.1.25\|172.16' | sort | uniq | wc|awk '{print \$1}'"
echo -
ssh root@192.1.2.223  "asterisk -rx 'sip show peers'| grep '192.1.25\|172.16' | sort | uniq| cut -f1 -d\/ "
echo ---pbx4
ssh root@192.1.2.221  "asterisk -rx 'sip show peers'| grep '192.1.25\|172.16' | sort | uniq | wc|awk '{print \$1}'"
echo -
ssh root@192.1.2.222  "asterisk -rx 'sip show peers'| grep '192.1.25\|172.16' | sort | uniq| cut -f1 -d\/ "
echo ---sit70
ssh root@192.1.2.221  "asterisk -rx 'sip show peers'| grep '192.1.25\|172.16' | sort | uniq | wc|awk '{print \$1}'"
echo -
ssh root@192.1.2.70 "netstat -n | grep '192.1.25\|172.16' | cut -f2 -d: | grep 80| sort | uniq | sed 's/\s\+/ /g' | cut -d' ' -f2"
echo ---sit71
ssh root@192.1.2.221  "asterisk -rx 'sip show peers'| grep '192.1.25\|172.16' | sort | uniq | wc|awk '{print \$1}'"
echo -
ssh root@192.1.2.71 "netstat -n | grep '192.1.25\|172.16' | cut -f2 -d: | grep 80| sort | uniq | sed 's/\s\+/ /g' | cut -d' ' -f2"
echo ---sit74
ssh root@192.1.2.221  "asterisk -rx 'sip show peers'| grep '192.1.25\|172.16' | sort | uniq | wc|awk '{print \$1}'"
echo -
ssh root@192.1.2.74 "netstat -n | grep '192.1.25\|172.16' | cut -f2 -d: | grep 80| sort | uniq | sed 's/\s\+/ /g' | cut -d' ' -f2"
echo ---84
ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.190 "/ppp active print" | awk '{print $2,$5}' | grep -v NAME | grep -v R
echo ---85
ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.191 "/ppp active print" | awk '{print $2,$5}' | grep -v NAME | grep -v R
echo ---145
ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.192 "/ppp active print" | awk '{print $2,$5}' | grep -v NAME | grep -v R
echo ---26
ssh -i /home/jgalvez/.ssh/id_rsa 192.1.5.193 "/ppp active print" | awk '{print $2,$5}' | grep -v NAME | grep -v R
