#!/bin/bash
echo pbx1
ssh root@192.1.2.221  "tail /var/log/asterisk/full | grep Wrong && asterisk -rx 'sip reload'"
echo pbx2
ssh root@192.1.2.220  "tail /var/log/asterisk/full | grep Wrong && asterisk -rx 'sip reload'"
echo pbx3
ssh root@192.1.2.223  "tail /var/log/asterisk/full | grep Wrong && asterisk -rx 'sip reload'"
echo pbx4
ssh root@192.1.2.223  "tail /var/log/asterisk/full | grep Wrong && asterisk -rx 'sip reload'"
