#!/bin/bash
echo pbx1
ssh root@pbx1  "tail /var/log/asterisk/full | grep Wrong && asterisk -rx 'sip reload'"
echo pbx2
ssh root@pbx2  "tail /var/log/asterisk/full | grep Wrong && asterisk -rx 'sip reload'"
echo pbx3
ssh root@pbx3  "tail /var/log/asterisk/full | grep Wrong && asterisk -rx 'sip reload'"
echo pbx4
ssh root@pbx4  "tail /var/log/asterisk/full | grep Wrong && asterisk -rx 'sip reload'"
